apiVersion: v1
kind: Service
metadata:
  labels:
    app: db-sts
    tier: db
  name: db
  namespace: dev
spec:
  ports:
    - port: 3306
      name: mysql
  selector:
    app: db-sts
    tier: db
  clusterIP: None