apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db-deploy
    tier: db
  name: db-deploy
  namespace: dev
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: db-deploy
      tier: db
  template:
    metadata:
      labels:
        app: db-deploy
        tier: db
    spec:
      containers:
      - image: mysql:8.0
        imagePullPolicy: IfNotPresent
        name : db
        #command: mysqld --default-authentication-plugin=mysql_native_password
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: toor
          - name: default-auth
            value: mysql_native_password
        ports:
        - containerPort: 3306
          name: mysql
      #   volumeMounts:
      #   - name: mysql-persistent-storage
      #     mountPath: /var/lib/mysql
      # volumes:
      # - name: mysql-persistent-storage
      #   persistentVolumeClaim:
      #     claimName: mysql-pvc
# create secrets.yaml to store mysql username and password.
# complete above spec using below link 
# https://kubernetes.io/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/#create-persistentvolumeclaims-and-persistentvolumes