apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: dev
  labels:
    app: db-sts
    tier: db
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /mnt/E/DO_NOT_TOUCH/kube_pv