apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: dev
spec:
  capacity:
    storage: 200Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage
  local:
    path: /mnt/E/DO_NOT_TOUCH/kube_db_pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - website-backend
          - website-backend-m03